apiVersion: apps/v1
kind: Deployment
metadata:
  name: armada-frontend
  labels:
    app: armada-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: armada-frontend
  template:
    metadata:
      labels:
        app: armada-frontend
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: armada-frontend
          image: {{ .Values.dockerHubName }}/armada-frontend:latest
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5