apiVersion: v1
kind: Service
metadata:
  name: armada-proxy-provider-service
spec:
  selector:
    app: armada-proxy-provider
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
