apiVersion: apps/v1
kind: Deployment
metadata:
 name: armada-backend
 labels:
   app: armada-backend
spec:
 replicas: 1
 selector:
   matchLabels:
     app: armada-backend
 template:
   metadata:
     labels:
       app: armada-backend
   spec:
{{- with .Values.imagePullSecrets }}
     imagePullSecrets:
{{- toYaml . | nindent 6 }}
{{- end }}
     containers:
       - name: armada-backend
         image: {{ .Values.dockerHubName }}/armada-backend:latest
         imagePullPolicy: {{ .Values.imagePullPolicy }}
         ports:
           - containerPort: 8000
         env:
           - name: SQL_SERVER_USER
             valueFrom:
               secretKeyRef:
                 name: armada-sql-server-secret
                 key: SQL_SERVER_USER
           - name: SQL_SERVER_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: armada-sql-server-secret
                 key: SQL_SERVER_PASSWORD
           - name: SQL_SERVER_DB
             valueFrom:
               secretKeyRef:
                 name: armada-sql-server-secret
                 key: SQL_SERVER_DB
           - name: SQL_SERVER_NAME
             valueFrom:
               secretKeyRef:
                 name: armada-sql-server-secret
                 key: SQL_SERVER_NAME
         resources:
           requests:
             memory: "64Mi"
             cpu: "50m"
           limits:
             memory: "256Mi"
             cpu: "200m"
         livenessProbe:
           httpGet:
             path: /docs
             port: 8000
           initialDelaySeconds: 10
           periodSeconds: 10
         readinessProbe:
           httpGet:
             path: /docs
             port: 8000
           initialDelaySeconds: 10
           periodSeconds: 5
