apiVersion: v1
kind: Service
metadata:
  name: armada-fingerprint-provider-service
spec:
  selector:
    app: armada-fingerprint-provider
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5005
  type: ClusterIP
